### ISSUE TITLE
It might be good if you could get more data from it

### ISSUE THREAD

**Issue by mhoivik** [er-hiba/Students_Scores#1]
Currently it only gets the average, but i would be nice if you could get like min, max, standard deviation etc.

**Comment by er-hiba** [comment]
> Currently it only gets the average, but i would be nice if you could get like min, max, standard deviation etc.

Thank you for your feedback.  I've made the requested enhancements to the code. It now sorts the scores and calculates not only the class average but also the median, standard deviation, minimum, maximum, and range. All of these statistics are displayed alongside the scores above the average.
