### ISSUE TITLE
Make the results screen on the left show the results when you av multiple graph open

### ISSUE THREAD

**Issue by mhoivik** [er-hiba/Students_Scores#8]
Currently it only has one graph support. Having support for 2(or more) graphs get it easier to compare result from example a test

**Comment by er-hiba** [comment]
> Currently it only has one graph support. Having support for 2(or more) graphs get it easier to compare result from example a test

Hey, thanks for the suggestion! I'd like to keep this program simple for now. It's meant to analyze scores and show graphs without comparing different classes. Keeping it focused this way makes it easier to use and understand. Thanks!
